create table if not exists public.consentimentos_privacidade (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  tipo text not null check (tipo in ('personalizacao', 'historico', 'dados_uso_anonimos', 'comunicacoes')),
  concedido boolean not null default false,
  versao_politica text not null default '1.0',
  origem text not null default 'central_privacidade',
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint consentimentos_privacidade_cliente_tipo_key unique (cliente_id, tipo)
);

comment on table public.consentimentos_privacidade is
  'Registro das escolhas de privacidade e consentimento do cliente no Vivo AdaptAI';

alter table public.consentimentos_privacidade enable row level security;
revoke all on table public.consentimentos_privacidade from anon, authenticated;
grant select, insert, update, delete on table public.consentimentos_privacidade to service_role;
grant usage, select on sequence public.consentimentos_privacidade_id_seq to service_role;

insert into public.consentimentos_privacidade
  (cliente_id, tipo, concedido, versao_politica, origem)
select
  c.id,
  consentimento.tipo,
  consentimento.concedido,
  '1.0',
  'migracao_preferencias'
from public.clientes c
cross join lateral (
  values
    ('personalizacao', coalesce((c.preferencias ->> 'personalizacao_atendimento')::boolean, true)),
    ('historico', coalesce((c.preferencias ->> 'salvar_historico')::boolean, true)),
    ('dados_uso_anonimos', coalesce((c.preferencias ->> 'dados_uso_anonimos')::boolean, false)),
    ('comunicacoes', coalesce((c.preferencias ->> 'notificacoes_novidades')::boolean, false))
) as consentimento(tipo, concedido)
on conflict (cliente_id, tipo) do nothing;
