alter table public.solicitacoes_atendimento
  add column if not exists atendente_auth_user_id uuid null,
  add column if not exists atendente_nome text null,
  add column if not exists assumida_em timestamptz null,
  add column if not exists ultima_resposta_em timestamptz null;

create index if not exists idx_solicitacoes_status_criada
  on public.solicitacoes_atendimento (status, criada_em desc);
create index if not exists idx_solicitacoes_atendente_status
  on public.solicitacoes_atendimento (atendente_auth_user_id, status);

create table if not exists public.atendimento_eventos (
  id bigint generated by default as identity primary key,
  solicitacao_id bigint not null references public.solicitacoes_atendimento(id) on delete cascade,
  ator_auth_user_id uuid null,
  ator_nome text not null,
  tipo_evento text not null check (tipo_evento in ('criada','assumida','resposta','concluida','cancelada','reaberta')),
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

comment on table public.atendimento_eventos is 'Trilha de auditoria da operacao de atendimento humano';
create index if not exists idx_atendimento_eventos_solicitacao
  on public.atendimento_eventos (solicitacao_id, criado_em);

alter table public.atendimento_eventos enable row level security;
revoke all on table public.atendimento_eventos from anon, authenticated;
revoke all on sequence public.atendimento_eventos_id_seq from anon, authenticated;
grant all on table public.atendimento_eventos to service_role;
grant usage, select on sequence public.atendimento_eventos_id_seq to service_role;
