create table if not exists public.notificacoes (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references public.clientes(id) on delete cascade,
  tipo text not null default 'sistema' check (tipo in ('sistema','atendimento','seguranca','novidade','lembrete')),
  titulo text not null check (char_length(titulo) between 1 and 120),
  mensagem text not null check (char_length(mensagem) between 1 and 500),
  link text null check (link is null or char_length(link) <= 255),
  lida boolean not null default false,
  arquivada boolean not null default false,
  metadados jsonb not null default '{}'::jsonb,
  criada_em timestamptz not null default now(),
  lida_em timestamptz null
);

comment on table public.notificacoes is 'Avisos pessoais exibidos no sino do Vivo AdaptAI';
comment on column public.notificacoes.cliente_id is 'Dono da notificacao';
comment on column public.notificacoes.metadados is 'Dados auxiliares nao sensiveis do aviso';

create index if not exists idx_notificacoes_cliente_criada
  on public.notificacoes (cliente_id, criada_em desc);
create index if not exists idx_notificacoes_cliente_nao_lida
  on public.notificacoes (cliente_id, lida)
  where arquivada = false;

alter table public.notificacoes enable row level security;
revoke all on table public.notificacoes from anon, authenticated;
revoke all on sequence public.notificacoes_id_seq from anon, authenticated;
grant all on table public.notificacoes to service_role;
grant usage, select on sequence public.notificacoes_id_seq to service_role;
